##### SCRIPT: SPectrometer for Ice Nucleation (SPIN) Level 0 #####
#' @author Christopher Rapp
#' @description
#'
#'
#'
# ---------------------------------------------------------------------------- #
##### SECTION: Libraries, Functions, Paths #####
#' These are directories that are in use for this code.
#' If files or scripts are renamed, moved, or changed, the code will NOT work!
#' Please keep updated for future readers of this code!
#'

{
  # Clears global environment and all saved variables
  rm(list = ls())
  gc(verbose = F)

  # Data wrangling libraries
  library(data.table)
  library(lubridate)
  library(dplyr)
  library(stringr)
  library(tidyr)

  # Plotting libraries
  library(ggplot2)
  library(ggpubr)
  library(ggsci)
  library(viridis)
  library(RColorBrewer)

  # Plotting parameters
  resolution.dpi = 400
  font.family = "Helvetica"

  # Set working directory
  setwd("~/Library/CloudStorage/Box-Box/Organosulfate Proxies")
  work.dir <- getwd()

  # Instrument time zone
  tz.c = "US/Eastern"

  #' @import
  #' Specify import directory
  import.spin = paste0(work.dir, "/SPIN/import/")

  #' @export
  #' Specify where to send plots and text files
  export.data = paste0(work.dir, "/SPIN/export/level0/")
  export.plot = paste0(work.dir, "/SPIN/export/plots/")

  #' @importFrom
  source(paste0("~/Documents/GitHub/functions/", "functions_microphysics.R"))
  source(paste0("~/Documents/GitHub/functions/", "functions_spin_plotting.R"))
}

# ---------------------------------------------------------------------------- #
##### SCRIPT: Start Loop #####
#'

{
  # Directories
  spin.dirs <- list.dirs(path = import.spin,
                         recursive = FALSE,
                         full.names = FALSE)

  # Add year extension to path
  spin.path <- paste0(import.spin, spin.dirs)

  # Pull POSIX style dates from directory names
  spin.dates <- as.Date(spin.dirs, format = '%Y%m%d')

  # Normal loop
  for (n in 1:length(spin.dates)){

    {
      print(paste0("Level 0 SPIN Data for ", spin.dates[n], " from directory ", spin.path[n]))

      # Memory management
      gc(verbose = F)

      # Code Timing
      pct <- proc.time()

      # Aggregate Data Segment
      {
        # ---------------------------------------------------------------------- #
        ##### SCRIPT: List Files #####
        #'

        {
          # List all SPIN files exported
          files.spin <- list.files(
            path = spin.path[n],
            recursive = TRUE,
            full.names = TRUE,
            pattern = '*.csv'
          )

          # List all log files
          files.log <- list.files(
            path = spin.path[n],
            recursive = TRUE,
            full.names = TRUE,
            pattern = '*.log'
          )

          # Filter files containing a possible string indicating low quality or not useable
          remove.filter <- c('temp', 'test', 'raw')

          # Apply word filter to remove files with key words
          files.spin <-
            files.spin[!grepl(paste(remove.filter, collapse = '|'),
                              ignore.case = T,
                              files.spin)]

          # Apply word filter to keep particle by particle data
          files.PbP <-
            files.spin[grepl(paste("PbP", collapse = '|'), ignore.case = T, files.spin)]

          # Only keep SPIN files, not PbP data or potentially saved pre-cooler files
          # Precooler data was originally saved into the SPIN directory but has since changed
          files.spin <-
            files.spin[!grepl(paste(c("PbP", "precooler"), collapse = '|'), ignore.case = T, files.spin)]

          # Data path
          export.data.path = paste0(export.data, spin.dirs[n], "/")

          # Check if export path exists
          # If it does not, create it
          if (!dir.exists(export.data.path)) {
            # Create a dated directory to send plots to
            dir.create(export.data.path, mode = "777")
          }

          # Plot path
          export.plot.path = paste0(export.plot, spin.dirs[n], "/")

          # Check if export path exists
          # If it does not, create it
          if (!dir.exists(export.plot.path)) {
            # Create a dated directory to send plots to
            dir.create(export.plot.path, mode = "777")
          }

          rm(remove.filter)
        }

        # ---------------------------------------------------------------------- #
        ##### SECTION: Data Wrangling - Log File #####
        #' This is information generated by SPIN software to record status and
        #' any operations occurring with the instrument
        #' Some errors reported are ironically errors themselves in that they do not
        #' accurately reflect conditions of the instrument e.g. artifacts of unplugged DAQ devices

        {
          print("SECTION: Data Wrangling - Log File")

          # Read in data using newline character as a separator
          # SPIN uses "\n" as a delimiter in log files
          tmp <- fread(files.log, fill = TRUE, sep = "\n")

          # Using the separate function to split the character column into two
          # This uses the regex pattern for a 24 time with a space after
          log.df <- tidyr::separate(tmp, col = 1, into = c("Time", "Message"),
                                    sep = "(?<=\\d{2}:\\d{2}:\\d{2}) "
                                    )

          # Extract date string from log file name
          log.df$Date <- as.Date(ymd(str_extract(files.log, "\\d{8}")))

          # Use run length encoding to find when a time shift across midnight occurs
          # Currently looks for times at which a 6 hour negative time shift happens
          switch.point = which(diff(rle(as.numeric(hms(log.df$Time)))$values) < -6*3600)
          if (length(switch.point) != 0){
            midnight.change = cumsum(rle(as.numeric(hms(log.df$Time)))$lengths)[switch.point] + 1

            log.df$Date[midnight.change:nrow(log.df)] <- as.Date(log.df$Date[1]) + 1
          }

          # Create a POSIX.ct object for further use
          log.df <- log.df %>%
            mutate(`Local Time` = as.POSIXct(paste0(log.df$Date, " ", log.df$Time),
              tz = tz.c
            ))

          dataLOG.df <- log.df %>%
            select(-c(`Time`, `Date`)) %>%
            select(c(`Local Time`, `Message`)) %>%
            arrange(`Local Time`) %>%
            mutate(`UTC Time` = with_tz(`Local Time`, tzone = "UTC"), .before = everything())

          # Determine start times of specific sequences
          # If the names of the sequences have changed in the software this won't catch them correctly
          sequence.start.tm = dataLOG.df$`Local Time`[str_which(dataLOG.df$Message, "Starting Sequence Startup IV.")]
          sequence.evrmp.tm = dataLOG.df$`Local Time`[str_which(dataLOG.df$Message, "Starting Sequence Ramp with Evap Ramp II.")]
          sequence.icing.tm = dataLOG.df$`Local Time`[str_which(dataLOG.df$Message, "Starting Sequence Fill & Empty Chamber II.")]
          sequence.ramps.tm = dataLOG.df$`Local Time`[str_which(dataLOG.df$Message, "Starting Sequence Update SPs from Ramp.")]
          stopping.start.tm = dataLOG.df$`Local Time`[str_which(dataLOG.df$Message, "Stopping Sequence Startup IV.")]

          rm(tmp, log.df, files.log)
        }

        # ---------------------------------------------------------------------- #
        ##### SECTION: Data Wrangling - Particle by Particle #####
        #'

        {
          print("SECTION: Data Wrangling - Particle by Particle")

          # Loop through list of files and create a dataframe of each
          PbP.ls <- lapply(files.PbP, function(x) {
            # Use data.table's fread to read in data
            # Fastest method in reading CSV's and least memory consuming
            # fill MUST equal FALSE with SPIN files
            tmp.df <- data.table::fread(
              paste0(x),
              na.strings = c("", "NA", "NaN"),
              fill = TRUE,
              strip.white = TRUE,
              stringsAsFactors = FALSE
            )

            if (any(str_detect(colnames(tmp.df), "IPT"))){
              setnames(
                tmp.df,
                old = c("End ms", "S", "IPT (msec)"),
                new = c("End (ms)", "S1", "IPT (ms)")
              )

              return(tmp.df)
            }
          })

          # Combine data.frames into one large data.frame
          dataPBP.df <-
            data.table::rbindlist(PbP.ls, use.names = T, fill = T)

          rm(PbP.ls, files.PbP)
        }

        # ---------------------------------------------------------------------- #
        ##### SECTION: Data Wrangling - SPIN #####
        #'

        {
          print("SECTION: Data Wrangling - SPIN")

          # Loop through list of files and create a dataframe of each
          data.ls <- lapply(files.spin, function(x) {
            # Use data.table's fread to read in data
            # Fastest method in reading CSV's and least memory consuming
            # fill MUST equal FALSE with SPIN files
            tmp.df <- data.table::fread(
              paste0(x),
              na.strings = c("", "NA", "NaN"),
              fill = FALSE,
              strip.white = TRUE,
              stringsAsFactors = FALSE
            )

            # Extract date and time from the filename using regular expression
            # (?<=...) is a positive-look behind assertion
            # SPIN files always follow this pattern
            tmp.date = str_extract(x, "(?<=SPIN\\d{3}\\S?)\\d{8}")
            tmp.time = str_extract(x, "(?<=SPIN\\d{3}\\S?\\d{8})\\d{6}")

            # Convert date string in filename to POSIXct POSIXt
            tmp.datetime = as.POSIXct(paste0(tmp.date, " ", tmp.time),
                                      format = "%Y%m%d %H%M%S",
                                      tz = tz.c)

            # Obtain a date for the file at midnight
            tmp.date = as.POSIXct(paste0(tmp.date, " ", "000000"),
                                  format = "%Y%m%d %H%M%S",
                                  tz = tz.c)

            # Create a POSIXct POSIXt object in the dataframe
            tmp.df <- tmp.df %>%
              mutate(`Start Time` = tmp.datetime, .before = everything()) %>%
              mutate(`Local Time` = `Time (sec)` + tmp.date,
                     .before = everything())

            return(tmp.df)
          })

          # Combine data.frames into one large data.frame
          # Column numbers must be the same length for each dataframe in order to merge using this function
          rawSPIN.df <- data.table::rbindlist(data.ls, use.names = T, fill = T)[-1]

          # Sort times in increasing order in case there are any irregularities
          rawSPIN.df <-
            rawSPIN.df[order(as.POSIXct(rawSPIN.df$`Local Time`, format = '%Y/%m/%d %H:%M:%S')),]

          # Remove potential missing time values
          rawSPIN.df <- rawSPIN.df[!is.na(rawSPIN.df$`Local Time`)]

          # Round times so unique times can be identified
          # May or may not apply, exists on some files but not consistent
          rawSPIN.df$`Local Time` <-
            round_date(rawSPIN.df$`Local Time`, unit = "1 seconds")

          # Remove duplicates introduced by the software
          rawSPIN.df <-
            dplyr::distinct(rawSPIN.df, `Local Time`, .keep_all = TRUE)

          # Set any NaN's to NA
          rawSPIN.df[is.na(rawSPIN.df)] <- NA

          # Calculate the duration of the experiment from the first time logged
          # This is offset as the start time is calculated from the filename
          rawSPIN.df <- rawSPIN.df %>%
            mutate(`Duration (s)` = round(as.numeric(`Local Time` - `Start Time`[1]))) %>%
            select(`Local Time`, `Start Time`, `Duration (s)`, everything())

          # Offset duration to correct for difference in logging time and software file creation
          rawSPIN.df$`Duration (s)` <- rawSPIN.df$`Duration (s)` - (first(rawSPIN.df$`Duration (s)`) - 1)

          # Generate a string containing the date for plotting
          date.c = unique(force_tz(as_date(rawSPIN.df$`Local Time`), 'America/New_York'))[1]

          #' Check if there is real data for the day
          #' If the compressor RPM is strictly zero, the instrument never entered
          #' the startup sequence
          if (max(rawSPIN.df$`Warm Cmpr (RPM)`) == 0) {
            # Print duration of loop and print date/status
            print(paste0(date.c, ' Empty, Elapsed Time (s) ', round((
              proc.time() - pct)[3], 2)))
            next
          }

          # Remove temporary variables
          rm(data.ls, files.spin)

          # ------------------------------------------------------------------------ #
          ##### SUBSECTION: Subset SPIN Data #####
          #' Combine all the SPIN data from the data list produced above
          #' Generate a secondary time column showing the duration of the experiment
          #' Subset data into groups that are later used in plotting
          #'

          {
            print("SECTION: Subset SPIN Data")

            # Create a string of the column names of the main dataframe
            tmp.nm = colnames(rawSPIN.df)

            # Indices of parameters that are not used
            indices.remove <- which(str_detect(tmp.nm, "Analog"))
            indices.remove <- append(indices.remove, which(str_detect(tmp.nm, "spare")))

            # Indices of binned particle data
            indices.bins <- which(str_detect(tmp.nm, "Bin\\s\\d+"))

            #  Indices of inlet valve status
            indices.inletvalve <- which(str_detect(tmp.nm, "Inlet Valve"))

            # Indices of relevant lamina variables
            indices.Lamina <- which(str_detect(tmp.nm, "SS%"))
            indices.Lamina <- append(indices.Lamina, which(str_detect(tmp.nm, "Lam")))
            indices.Lamina <- append(indices.Lamina, which(str_detect(tmp.nm, "\\(mm\\)")))

            # Indices of temperature setpoints
            indices.SP <- which(str_detect(tmp.nm, "SP"))

            # Indices of refrigerant variables
            indices.refrigerant <- which(str_detect(tmp.nm, "ColdTopRefr"))
            indices.refrigerant <- append(indices.refrigerant, which(str_detect(tmp.nm, "ColdMidRefr")))
            indices.refrigerant <- append(indices.refrigerant, which(str_detect(tmp.nm, "ColdBotRefr")))
            indices.refrigerant <- append(indices.refrigerant, which(str_detect(tmp.nm, "WarmTopRefr")))
            indices.refrigerant <- append(indices.refrigerant, which(str_detect(tmp.nm, "WarmBotRefr")))
            indices.refrigerant <- append(indices.refrigerant, which(str_detect(tmp.nm, "EvapRefr")))

            # Indices of flow rates
            indices.flows <- which(str_detect(tmp.nm, "Flow"))

            # Indices of pressure
            indices.pressure <- which(str_detect(tmp.nm, "Pressure"))

            # Indices of compressor values
            indices.cmpr <- which(str_detect(tmp.nm, "(?=.(psi))"))
            indices.cmpr <- append(indices.cmpr, which(str_detect(tmp.nm, ".*RPM")))
            indices.cmpr <- append(indices.cmpr, which(str_detect(tmp.nm, "Fault")))
            indices.cmpr <- append(indices.cmpr, which(str_detect(tmp.nm, "Cold.*(1st).*\\(C\\)")))
            indices.cmpr <- append(indices.cmpr, which(str_detect(tmp.nm, "Cold.*(2nd).*\\(C\\)")))
            indices.cmpr <- append(indices.cmpr, which(str_detect(tmp.nm, "Warm.*Cmpr.*\\(C\\)")))

            # Thermocouple Values
            indices.coldTCs <- which(str_detect(tmp.nm, "C\\d{0,2}\\(\\w\\)"))
            indices.warmTCs <- which(str_detect(tmp.nm, "W\\d{0,2}\\(\\w\\)"))

            # Heaters
            indices.ColdHeat <- which(str_detect(tmp.nm, "CH\\d+"))
            indices.ColdHeat <- append(indices.ColdHeat, which(str_detect(tmp.nm, "HeatCold_\\d+")))
            indices.WarmHeat <- which(str_detect(tmp.nm, "WH\\d+"))
            indices.WarmHeat <- append(indices.WarmHeat, which(str_detect(tmp.nm, "HeatWarm_\\d+")))

            # OPC Status
            indices.OPC <- which(str_detect(tmp.nm, "bandwidth"))
            indices.OPC <- append(indices.OPC, which(str_detect(tmp.nm, "baseline")))
            indices.OPC <- append(indices.OPC, which(str_detect(tmp.nm, "oversize")))
            indices.OPC <- append(indices.OPC, which(str_detect(tmp.nm, "Laser")))
            indices.OPC <- append(indices.OPC, which(str_detect(tmp.nm, "transit")))
          }

          # ------------------------------------------------------------------------ #
          ##### SUBSECTION: Flows and Chamber Pressure #####
          #'

          {
            dataFLOW.df <- rawSPIN.df %>%
              select(`Local Time`, all_of(c(indices.flows, indices.pressure)))

            # Rename the variables to a more friendly format
            tmp.nm <- str_squish(gsub('([[:upper:]])', ' \\1', colnames(dataFLOW.df)))
            tmp.nm = str_replace(tmp.nm, "S P", "SP")
            tmp.nm = str_replace(tmp.nm, " S L P M", "SLPM")
            tmp.nm = str_replace(tmp.nm, "slpm", "SLPM")
            tmp.nm = str_replace(tmp.nm, " L P M", "LPM")
            tmp.nm = str_replace(tmp.nm, "Flow\\(", "Flow (")
            tmp.nm = str_replace(tmp.nm, "\\(mbar", " (mbar")
            tmp.nm = str_replace(tmp.nm, "Flow%", "Flow %")
            tmp.nm = str_replace(tmp.nm, "Vol ", "Volumetric")
            tmp.nm = str_replace(tmp.nm, "cFlow", "c Flow")

            # Change column names
            setnames(dataFLOW.df, new = tmp.nm)
            setnames(dataFLOW.df, old = "Volumetric Flow (LPM)", new = "Sheath Volumetric Flow (LPM)")

            # Calculate total flow variable for volumetric flow
            dataFLOW.df <- dataFLOW.df %>%
              mutate(`Total Flow (LPM)` = `Sample Volumetric Flow (LPM)` + `Sheath Volumetric Flow (LPM)`)

            # Remove two variables that appear to be constants and reorder
            dataFLOW.df <- dataFLOW.df %>%
              select(c(colnames(dataFLOW.df)[1], sort(colnames(dataFLOW.df)[-1]))) %>%
              select(!c(`Closing Pressure`, `Sheath Flow Memory`))

            rm(indices.flows, indices.pressure, tmp.nm)
          }

          # ------------------------------------------------------------------------ #
          ##### SUBSECTION: Bin Data #####
          #' Binned aerosol data

          {
            # Midpoint diameter: NANOMETERS
            bins.nm = c(
              550,
              650,
              750,
              850,
              950,
              1500,
              2500,
              3500,
              4500,
              5500,
              6500,
              7500,
              8500,
              9500,
              10500,
              11500,
              12500,
              13500,
              14500
            )

            # Midpoint diameter: MICROMETERS
            bins.nm = bins.nm / 1000

            # Subset bins
            # Drop the first as it is not defined by a lower limit
            dataBINS.df <- rawSPIN.df %>%
              select(all_of(indices.bins)[-1]) %>%
              setnames(., new = paste0(bins.nm))

            # Append the time column to the front of the data.frame
            # Add a column indicated the units of the binned aerosol data
            dataBINS.df <- dataBINS.df %>%
              mutate(`Local Time` = rawSPIN.df$`Local Time`, .before = everything()) %>%
              mutate(`Units` = "#/s")

            rm(indices.bins, bins.nm)
          }

          # ------------------------------------------------------------------------ #
          ##### SUBSECTION: Inlet Filter Data #####
          #'

          {
            # 0 means closed
            # 1 means open
            dataFLTR.df <- rawSPIN.df %>%
              select(`Local Time`, all_of(indices.inletvalve)) %>%
              mutate(`Inlet Valve Inlet/Zero` = as.numeric(`Inlet Valve Inlet/Zero`))

            setnames(dataFLTR.df, old = "Inlet Valve Inlet/Zero", new = "Inlet Filter ON")

            # Change booleans to match the column name
            dataFLTR.df$`Inlet Filter ON` <- as.numeric(!dataFLTR.df$`Inlet Filter ON`)

            rm(indices.inletvalve)
          }

          # ------------------------------------------------------------------------ #
          ##### SUBSECTION: Lamina Conditions #####
          #' Supersaturation and humidity
          #' Lamina temperature

          {
            dataLAM.df <- rawSPIN.df %>%
              select(`Local Time`, all_of(indices.Lamina))

            setnames(dataLAM.df,
                     old = colnames(dataLAM.df)[-1],
                     new = c("Lamina SS% Liquid",
                             "Lamina SS% Ice",
                             "Lamina Temp (C)",
                             "Lamina Centerline Ratio",
                             "Lamina Centerline Distance from Warm Wall (mm)",
                             "Lamina Thickness (mm)",
                             "Lamina Saturation Pressure Liquid/Ice",
                             "Nearside Distance (mm)",
                             "Farside Distance (mm)"
                             ))

            # Final processing
            # Convert to saturation ratio (S) rather than SS%
            # SS% in this case means percent above 100%
            # SS% = (S-1)*100
            # Also add dewpoint value
            dataLAM.df <- dataLAM.df %>%
              mutate(`Lamina S Liquid` = `Lamina SS% Liquid`/100 + 1) %>%
              mutate(`Lamina S Ice` = `Lamina SS% Ice`/100 + 1) %>%
              mutate("Dewpoint" = rawSPIN.df$`Dew Point (C)`)

            rm(indices.Lamina)
          }

          # ------------------------------------------------------------------------ #
          ##### SUBSECTION: Thermcouples #####
          #' Thermocouple variables

          {
            # Subset set points
            dataTCSP.df <- rawSPIN.df %>%
              select(all_of(c(indices.SP))) %>%
              select(`Warm_SP`, `Cold_SP`, `Evap_SP`) %>%
              setnames(., new = c("Warm Wall SP", "Cold Wall SP", "Evaporation SP"))

            # Create a vector of values to detect spikes in wall setpoints
            dataTCSP.df <- dataTCSP.df %>%
              mutate(`CWSP Noise` = append(0, abs(diff(`Cold Wall SP`)))) %>%
              mutate(`WWSP Noise` = append(0, abs(diff(`Warm Wall SP`)))) %>%
              mutate("Local Time" = rawSPIN.df$`Local Time`, .before = everything())

            # Replace erroneous spikes from interuptions in the program with NAs
            dataTCSP.df$`Cold Wall SP`[which(dataTCSP.df$`CWSP Noise` > 22)] <- NA
            dataTCSP.df$`Warm Wall SP`[which(dataTCSP.df$`WWSP Noise` > 22)] <- NA

            # Drop temporary columns
            dataTCSP.df <- dataTCSP.df %>%
              select(-c(`CWSP Noise`, `WWSP Noise`))

            # Evaporation setpoint prior to the experiment time isn't a valid variable
            dataTCSP.df[which(rawSPIN.df$`Local Time` <= first(sequence.ramps.tm)), "Evaporation SP"] <- NA

            # Subset cold wall thermocouples
            dataCTC.df <- rawSPIN.df %>%
              select(all_of(c(indices.coldTCs))) %>%
              setnames(., new = c(str_remove(colnames(.), "\\(C\\)"))) %>%
              mutate("Local Time" = rawSPIN.df$`Local Time`, .before = everything())

            # Subset cold wall thermocouples
            dataWTC.df <- rawSPIN.df %>%
              select(all_of(c(indices.warmTCs))) %>%
              setnames(., new = c(str_remove(colnames(.), "\\(C\\)"))) %>%
              mutate("Local Time" = rawSPIN.df$`Local Time`,
                     .before = everything())

            rm(indices.coldTCs, indices.warmTCs)
          }

          # -------------------------------------------------------------------- #
          ##### SUBSECTION: Compressor Data #####
          #' Compressor variables

          {
            #' Subset from rawSPIN.df
            #' Force to numeric
            dataCMPR.df <- rawSPIN.df %>%
              select(all_of(indices.cmpr)) %>%
              as.matrix() %>%
              as.data.frame() %>%
              mutate(`Local Time` = rawSPIN.df$`Local Time`, .before = everything()) %>%
              mutate(`Duration(s)` = rawSPIN.df$`Duration(s)`, .before = everything())

            # Rename the variables to a more friendly format
            tmp.nm = str_replace(colnames(dataCMPR.df), "Temp", "Temperature")
            tmp.nm = str_remove_all(tmp.nm, "Cmpr ")
            tmp.nm = str_remove_all(tmp.nm, "st")
            tmp.nm = str_remove_all(tmp.nm, "nd")
            tmp.nm = str_replace(tmp.nm, "Pres", "Pressure")

            setnames(dataCMPR.df, new = tmp.nm)

            # Add power supply current data
            dataCMPR.df$`Power Supply Current` <- rawSPIN.df$`Power Supply Curr (A)`

            # Remove unrealistic CMPR Out Temperature
            dataCMPR.df[dataCMPR.df < -273] <- NA
            dataCMPR.df$`Cold 2 Out Temperature (C)`[dataCMPR.df$`Cold 2 Out Temperature (C)` > 200] <- NA

            # Reorder columns
            dataCMPR.df <- dataCMPR.df %>%
              select(c(colnames(dataCMPR.df)[1], sort(colnames(dataCMPR.df)[-1])))

            rm(indices.cmpr, tmp.nm)
          }

          # ------------------------------------------------------------------------ #
          ##### SUBSECTION: Cooling System #####
          #'

          {
            dataREFR.df <- rawSPIN.df %>%
              select(`Local Time`, all_of(c(indices.refrigerant)))

            # Rename the variables to a more friendly format
            tmp.nm <- str_squish(gsub('([[:upper:]])', ' \\1', colnames(dataREFR.df)))
            tmp.nm = str_remove(tmp.nm, "_")
            tmp.nm = str_remove(tmp.nm, "Refr")
            tmp.nm = str_replace(tmp.nm, "S P", "SP")
            tmp.nm = str_replace(tmp.nm, "P V", "PV")
            tmp.nm = str_squish(tmp.nm)

            # Change column names
            setnames(dataREFR.df, new = tmp.nm)

            # Reorder dataframe
            dataREFR.df <- dataREFR.df %>%
              select(c(colnames(dataREFR.df)[1], sort(colnames(dataREFR.df)[-1])))

            dataCH.df <- rawSPIN.df %>%
              select(`Local Time`, all_of(c(indices.ColdHeat)))

            # Rename the variables to a more friendly format
            tmp.nm = str_replace(colnames(dataCH.df), "_", " ")
            tmp.nm = str_replace(tmp.nm, "OnTime", "On Time")
            tmp.nm = str_replace(tmp.nm, "OffTime", "Off Time")
            tmp.nm = str_replace(tmp.nm, "HeatCold", "Heat Cold")

            # Change column names
            setnames(dataCH.df, new = tmp.nm)

            # Reorder dataframe
            dataCH.df <- dataCH.df %>%
              select(c(colnames(dataCH.df)[1], sort(colnames(dataCH.df)[-1])))

            dataWH.df <- rawSPIN.df %>%
              select(`Local Time`, all_of(c(indices.WarmHeat)))

            # Rename the variables to a more friendly format
            tmp.nm = str_replace(colnames(dataWH.df), "_", " ")
            tmp.nm = str_replace(tmp.nm, "OnTime", "On Time")
            tmp.nm = str_replace(tmp.nm, "OffTime", "Off Time")
            tmp.nm = str_replace(tmp.nm, "HeatWarm", "Heat Warm")

            # Change column names
            setnames(dataWH.df, new = tmp.nm)

            # Reorder dataframe
            dataWH.df <- dataWH.df %>%
              select(c(colnames(dataWH.df)[1], sort(colnames(dataWH.df)[-1])))

            rm(indices.refrigerant, indices.ColdHeat, indices.WarmHeat)
          }

          # ------------------------------------------------------------------------ #
          ##### SUBSECTION: OPC System Variables #####
          #'

          {
            dataOPC.df <- rawSPIN.df %>%
              select(`Local Time`, all_of(c(indices.OPC)))

            # Rename the variables to a more friendly format
            tmp.nm = str_replace(colnames(dataOPC.df), "low", "Low")
            tmp.nm = str_replace(tmp.nm, "hi", "High")
            tmp.nm = str_replace(tmp.nm, "sizer", "Sizer")
            tmp.nm = str_replace(tmp.nm, "baseline", "Baseline")
            tmp.nm = str_replace(tmp.nm, "bandwidth", "Bandwidth")
            tmp.nm = str_replace(tmp.nm, "oversize", "Oversize")
            tmp.nm = str_replace(tmp.nm, "total transit time", "Total Transit Time")

            # Change column names
            setnames(dataOPC.df, new = tmp.nm)

            # Reorder dataframe
            dataOPC.df <- dataOPC.df %>%
              select(c(colnames(dataOPC.df)[1], sort(colnames(dataOPC.df)[-1])))

            rm(indices.OPC, tmp.nm)
          }
        }

        # ---------------------------------------------------------------------- #
        ##### SECTION: Aggregate Data #####
        #' Combine datasets from above into one dataframe
        #' Create a finalized dataset for any experiments
        #'

        {
          print("SECTION: Aggregate Data")

          # Combine subsets
          dataSPIN.df <-
            cbind(
              dataBINS.df,
              dataFLTR.df,
              dataFLOW.df,
              dataLAM.df,
              dataOPC.df,
              dataTCSP.df,
              dataCTC.df,
              dataWTC.df,
              dataCMPR.df,
              dataREFR.df,
              dataCH.df,
              dataWH.df,
              rawSPIN.df[, 1:7]
            )

          dataSPIN.df <- subset(dataSPIN.df, select = !duplicated(names(dataSPIN.df))) %>%
            select(c(`Local Time`, `Start Time`, `Time (sec)`, `Duration (s)`,
                     `Lamina S Ice`, `Lamina S Liquid`), everything())

          rm(dataBINS.df, dataFLTR.df, dataFLOW.df, dataLAM.df, dataOPC.df,
             dataTCSP.df, dataCTC.df, dataWTC.df, dataCMPR.df, dataREFR.df,
             dataCH.df, dataWH.df)
        }
      }

      # ---------------------------------------------------------------------- #
      ##### PLOTTING: Overview Plot #####
      #'

      # Overview plot
      {
        #' Plot Cold Wall SP
        #' Plot Warm Wall SP
        #' Plot Lamina SSice
        #' Plot Lamina SSliquid
        #' Plot Lamina temperature
        #' Plot Inlet Valve Position
        #'
        title.main <- paste0("Spectrometer for Ice Nucleation (SPIN)")
        title.sub <- paste0("Experiment Overview: ", date.c)

        plot.filename = paste0(export.plot.path, date.c, ' Overview', '.png')

        print(paste0("Plotting: ", plot.filename))

        overview.plot(title.main,
                      title.sub,
                      data = dataSPIN.df,
                      sequence.start.tm,
                      sequence.evrmp.tm,
                      sequence.icing.tm,
                      sequence.ramps.tm,
                      stopping.start.tm,
                      plot.filename,
                      plot.width = 14,
                      plot.height = 8,
                      plot.resolution.dpi = 300)
      }

      # ---------------------------------------------------------------------- #
      ##### PLOTTING: Compressor Plot #####
      #'

      {
        {
          cmpr.pressure <- colnames(dataSPIN.df)[str_which(colnames(dataSPIN.df), "Pressure \\(psi\\)")]
          cmpr.fault <- colnames(dataSPIN.df)[str_which(colnames(dataSPIN.df), "Fault")]
          df1 = dataSPIN.df %>%
            select(all_of(c(cmpr.pressure, cmpr.fault))) %>%
            mutate(`Local Time` = dataSPIN.df$`Local Time`, .before = everything())

          setnames(df1, old = colnames(df1), new = c("Local Time", str_replace(cmpr.pressure, "\\s+Pressure\\s+\\(psi\\)", ""), cmpr.fault))

          df1[df1 == 0] <- NA
        }

        {
          cmpr.temperature <- colnames(dataSPIN.df)[str_which(colnames(dataSPIN.df), "Temperature")]
          df2 = dataSPIN.df %>%
            select(all_of(cmpr.temperature)) %>%
            mutate(`Local Time` = dataSPIN.df$`Local Time`, .before = everything())

          setnames(df2, old = colnames(df2), new = c("Local Time", str_replace(cmpr.temperature, '\\s+Temperature\\s{1}\\(C\\)', "")))
        }

        {
          cmpr.rpm <- colnames(dataSPIN.df)[str_which(colnames(dataSPIN.df), "\\(RPM\\)")]
          df3 = dataSPIN.df %>%
            select(all_of(cmpr.rpm)) %>%
            mutate(`Local Time` = dataSPIN.df$`Local Time`, .before = everything())

          setnames(df3, old = colnames(df3), new = c("Local Time", str_replace(cmpr.rpm, "\\s+\\(RPM\\)", "")))
        }

        # Make paired color palette
        brewer.extract.f <- function(pal) brewer.pal(brewer.pal.info[pal, "maxcolors"], pal)
        paired.colors <- brewer.extract.f("Paired")

        title.main <- paste0("Spectrometer for Ice Nucleation (SPIN)")
        title.sub <- paste0("Compressor Performance: ", date.c)

        plot.filename = paste0(export.plot.path, date.c, ' Compressors', '.png')

        print(paste0("Plotting: ", plot.filename))

        Stacked.Time.Series(
          title.main = title.main,
          title.sub = title.sub,
          type = "point",
          df1 = df1,
          df2 = df2,
          df3 = df3,
          y1.limits = c(floor(min(df1[, 2:ncol(df1)], na.rm = T)), ceiling(max(df1[, 2:ncol(df1)], na.rm = T))),
          y2.limits = c(floor(min(df2[, 2:ncol(df2)], na.rm = T)), ceiling(max(df2[, 2:ncol(df2)], na.rm = T))),
          y3.limits = c(0, ceiling(max(df3[, 2:ncol(df3)], na.rm = T))),
          y1.label = "Pressure (psi)",
          y2.label = "Temperature (\u00B0C)",
          y3.label = "RPM",
          y1.nbreaks = 10,
          y2.nbreaks = 10,
          y3.nbreaks = 10,
          x.breaks = "30 min",
          plot.filename = plot.filename,
          plot.height = 10,
          plot.width = 12,
          col.palette1 = paired.colors,
          col.palette2 = paired.colors,
          col.palette3 = paired.colors)

        # Compressor load and power supply current
        {
          tmp1 <- df3 %>%
            select(c(str_which(colnames(df3), "SP", negate = T))) %>%
            select(!`Local Time`) %>%
            rowMeans(.)

          tmp2 <- dataSPIN.df %>%
            select(`Power Supply Current`) %>%
            cbind(tmp1) %>%
            rename(`Mean Compressor RPM` = tmp1) %>%
            mutate(`Local Time` = dataSPIN.df$`Local Time`)

          gg1 <- ggplot(tmp2, aes(x = `Mean Compressor RPM`, y = `Power Supply Current`)) +
            geom_point(size = 0.1, shape = 1) +
            stat_smooth(formula = y ~ x, method = "lm", level = 0.95, aes(x = `Mean Compressor RPM`, y = `Power Supply Current`), color = "red") +
            labs(title = paste0(date.c, " Power Supply and Compressor Load")) +
            ylab("Power Supply Current (Amps)") +
            theme(
              plot.title = element_text(),
              plot.subtitle = element_text(color = "gray25"),
              panel.background = element_rect(fill = "white"),
              panel.grid.major.x = element_line(colour = "gray90", linewidth = 0.1),
              panel.grid.major.y = element_line(colour = "grey80", linewidth = 0.1),
              panel.grid.minor = element_line(colour = "grey80", linewidth = 0.1),
              panel.border = element_rect(colour = "black", fill = NA, linewidth = 0.5),
              axis.text.y.right = element_blank(),
              axis.title.x = element_text(vjust = -2),
              axis.title.y.right = element_blank(),
              axis.text.x = element_text(angle = 90),
              axis.ticks.x = element_line(linewidth = 0.5),
              axis.ticks.y = element_line(linewidth = 0.5),
              axis.ticks.length = unit(1, "mm"),
              plot.margin = unit(c(0.2, 1, 0.2, 0.1), "cm"),
              legend.title = element_blank(),
              legend.background = element_blank(),
              legend.key = element_blank(),
              legend.position = "none",
              strip.background = element_rect(fill = "gray75"),
            )

          # Convert to long format for easier plotting
          tmp2.long <- tmp2 %>%
            pivot_longer(
              cols = !"Local Time",
              names_to = "Variable",
              values_to = "Value"
            ) %>%
            filter(`Variable` == "Power Supply Current")

          gg2 <-
            ggplot(data = tmp2.long, aes(x = `Variable`, y = `Value`)) +
            stat_boxplot(geom = "errorbar", na.rm = T) +
            geom_boxplot(aes(fill = `Variable`), outlier.shape = '.', na.rm = T, outlier.colour = "red") +
            theme_minimal() +
            ylab("") +
            xlab("") +
            scale_y_continuous(breaks = seq(0, 100, 10)) +
            theme(
              plot.title = element_text(),
              plot.subtitle = element_text(color = "gray25"),
              panel.background = element_rect(fill = "white"),
              panel.grid.major.x = element_line(colour = "gray90", linewidth = 0.1),
              panel.grid.major.y = element_line(colour = "grey80", linewidth = 0.1),
              panel.grid.minor = element_line(colour = "grey80", linewidth = 0.1),
              panel.border = element_rect(colour = "black", fill = NA),
              axis.title.x = element_blank(),
              axis.text.y.right = element_blank(),
              axis.ticks.x = element_line(size = 0.5),
              axis.ticks.y = element_line(size = 0.5),
              axis.ticks.length = unit(1, "mm"),
              plot.margin = unit(c(0.2, 1, 0.2, 0.1), "cm"),
              legend.title = element_blank(),
              legend.position = "none"
            )

          tmp.gg <- ggarrange(gg1, gg2, nrow = 1, align = 'h', widths = c(3, 1))

          plot.filename = paste0(export.plot.path, date.c,
                                 ' Compressor Power',
                                 '.png')

          print(paste0("Plotting: ", plot.filename))

          ggsave(
            plot.filename,
            tmp.gg,
            width = 10,
            height = 8,
            dpi = 400,
            units = "in",
            bg = "#ffffff"
          )
        }

        rm(df1, df2, df3, cmpr.pressure, cmpr.temperature, cmpr.fault, cmpr.rpm, tmp1, tmp2, tmp2.long, gg1, gg2)
      }

      # ---------------------------------------------------------------------- #
      ##### PLOTTING: Thermocouples Overview #####
      #'
      {
        {
          coldTCs <- colnames(dataSPIN.df)[str_which(colnames(dataSPIN.df), "C\\d+")]
          df1 = dataSPIN.df %>%
            select(all_of(coldTCs)) %>%
            mutate(`Local Time` = dataSPIN.df$`Local Time`, .before = everything())
        }

        {
          warmTCs <- colnames(dataSPIN.df)[str_which(colnames(dataSPIN.df), "W\\d+")]
          df2 = dataSPIN.df %>%
            select(all_of(warmTCs)) %>%
            mutate(`Local Time` = dataSPIN.df$`Local Time`, .before = everything())
        }

        title.main <- paste0("Spectrometer for Ice Nucleation (SPIN)")
        title.sub <- paste0("Thermocouples: ", date.c)

        plot.filename = paste0(export.plot.path, date.c, ' Thermocouples Overview', '.png')

        print(paste0("Plotting: ", plot.filename))

        Stacked.Time.Series(
          title.main = title.main,
          title.sub = title.sub,
          type = "line",
          df1 = df1,
          df2 = df2,
          cutoff.time = first(df1$`Local Time`),
          y1.limits = c(floor(min(df1[, 2:ncol(df1)], na.rm = T)), ceiling(max(df1[, 2:ncol(df1)], na.rm = T))),
          y2.limits = c(floor(min(df2[, 2:ncol(df2)], na.rm = T)), ceiling(max(df2[, 2:ncol(df2)], na.rm = T))),
          y1.label = "Temperature (\u00B0C)",
          y2.label = "Temperature (\u00B0C)",
          y1.nbreaks = 20,
          y2.nbreaks = 20,
          x.breaks = "30 min",
          plot.filename = plot.filename,
          plot.height = 10,
          plot.width = 12,
          col.palette1 = viridis_pal(option = "D", begin = 0.2)(16),
          col.palette2 = viridis_pal(option = "B", begin = 0.2)(16))

        rm(df1, df2, coldTCs, warmTCs)
      }

      # ---------------------------------------------------------------------- #
      ##### PLOTTING: Flows and Pressure #####
      #'

      # Flows and Chamber Pressure
      {
        {
          flows.volumetric <- colnames(dataSPIN.df)[str_which(colnames(dataSPIN.df), "\\(LPM\\)")]
          df1 = dataSPIN.df %>% select(all_of(flows.volumetric))
          df1 <- df1 %>%
            mutate(`Local Time` = dataSPIN.df$`Local Time`, .before = everything())
        }

        {
          flows.standard <- colnames(dataSPIN.df)[str_which(colnames(dataSPIN.df), "\\(SLPM\\)")]
          df2 = dataSPIN.df %>%
            select(all_of(flows.standard)) %>%
            mutate(`Local Time` = dataSPIN.df$`Local Time`, .before = everything())
        }

        {
          pressure <- colnames(dataSPIN.df)[str_which(colnames(dataSPIN.df), "Chamber Pressure")]
          df3 = dataSPIN.df %>%
            select(all_of(pressure)) %>%
            mutate(`Local Time` = dataSPIN.df$`Local Time`, .before = everything())
        }

        df1 <- df1 %>%
          filter(`Sample Volumetric Flow (LPM)` > quantile(`Sample Volumetric Flow (LPM)`, probs = c(0.0025), na.rm = T) &
                   `Sample Volumetric Flow (LPM)` < quantile(`Sample Volumetric Flow (LPM)`, probs = c(0.9975), na.rm = T)) %>%
          filter(`Total Flow (LPM)` > quantile(`Total Flow (LPM)`, probs = c(0.0025), na.rm = T) &
                   `Total Flow (LPM)` < quantile(`Total Flow (LPM)`, probs = c(0.9975), na.rm = T))

        df3 <- df3 %>%
          filter(`Chamber Pressure (mbar)` > quantile(df3$`Chamber Pressure (mbar)`, probs = c(0.0025), na.rm = T))

        title.main <- paste0("Spectrometer for Ice Nucleation (SPIN)")
        title.sub <- paste0("Flow Rates and Chamber Pressure: ", date.c)

        plot.filename = paste0(export.plot.path, date.c, ' Flows', '.png')

        # Make paired color palette
        brewer.extract.f <- function(pal) brewer.pal(brewer.pal.info[pal, "maxcolors"], pal)
        paired.colors <- brewer.extract.f("Paired")

        print(paste0("Plotting: ", plot.filename))

        Stacked.Time.Series(
          title.main = title.main,
          title.sub = title.sub,
          type = "line",
          df1 = df1,
          df2 = df2,
          df3 = df3,
          cutoff.time = first(df1$`Local Time`),
          y1.limits = c(floor(min(df1[, 2:ncol(df1)], na.rm = T)), ceiling(max(df1[, 2:ncol(df1)], na.rm = T))),
          y2.limits = c(floor(min(df2[, 2:ncol(df2)], na.rm = T)), ceiling(max(df2[, 2:ncol(df2)], na.rm = T))),
          y3.limits = c(floor(min(df3[, 2:ncol(df3)], na.rm = T)), ceiling(max(df3[, 2:ncol(df3)], na.rm = T))),
          y1.label = "Volumetric Flow (LPM)",
          y2.label = "Standardized Flow (SLPM)",
          y3.label = "Pressure (mBar)",
          y1.nbreaks = 10,
          y2.nbreaks = 10,
          y3.nbreaks = 10,
          x.breaks = "30 min",
          plot.filename = plot.filename,
          plot.height = 10,
          plot.width = 12,
          col.palette1 = paired.colors,
          col.palette2 = paired.colors,
          col.palette3 = paired.colors)

        rm(df1, df2, df3, flows.standard, flows.volumetric, pressure)
      }

      # ---------------------------------------------------------------------- #
      ##### SECTION: Thermocouple Subsetting #####
      #'

      {
        {
          coldTCs <- colnames(dataSPIN.df)[str_which(colnames(dataSPIN.df), "C\\d+")]
          coldTCs.df = dataSPIN.df %>% select(`Local Time`, all_of(coldTCs))
        }

        {
          warmTCs <- colnames(dataSPIN.df)[str_which(colnames(dataSPIN.df), "W\\d+")]
          warmTCs.df = dataSPIN.df %>% select(`Local Time`, all_of(warmTCs))
        }

        # Identify times 5 minutes after any startup sequence to remove
        # This will sway any statistics as the thermocouples exhibit large swings
        if (length(sequence.start.tm) != 0){

          remove.c <- NULL
          for (i in 1:length(sequence.start.tm)){

            start = sequence.start.tm[i]
            end = start + 5*60
            remove.c <- append(remove.c, seq.POSIXt(start, end, by = "1 sec"))
          }
        }

        coldTCs.df <- coldTCs.df %>%
          filter(!`Local Time` %in% remove.c)

        warmTCs.df <- warmTCs.df %>%
          filter(!`Local Time` %in% remove.c)

        # Remove values after icing
        if(length(sequence.icing.tm) != 0){

          start = sequence.icing.tm[1]
          end = start + 30*60

          coldTCs.df <- coldTCs.df %>%
            filter(!`Local Time` %in% seq.POSIXt(start, end, by = "1 sec"))

          warmTCs.df <- warmTCs.df %>%
            filter(!`Local Time` %in% seq.POSIXt(start, end, by = "1 sec"))
        }

        # Was an initial cooldown ever intiated? If so apply filter
        if(length(which(dataSPIN.df$`Warm Wall SP` == -25)) != 0){

          # Time at which it is hit will be the same for cold and warm wall
          start = dataSPIN.df$`Local Time`[first(which(dataSPIN.df$`Warm Wall SP` == -25))]

          coldTCs.df <- coldTCs.df %>%
            filter(`Local Time` > start)

          warmTCs.df <- warmTCs.df %>%
            filter(`Local Time` > start)
        }
      }

      # ---------------------------------------------------------------------- #
      ##### PLOTTING: Thermocouple Standard Deviations #####
      #'

      {
        # Calculate 2 minute running standard deviations of cold thermocouples
        coldTCs.SD.df <- as.data.frame(zoo::rollapplyr(coldTCs.df[, 2:17], 120, sd, fill = NA)) %>%
          mutate(`Local Time` = coldTCs.df$`Local Time`, .before = everything())

        # Calculate 2 minute running standard deviations of warm thermocouples
        warmTCs.SD.df <- as.data.frame(zoo::rollapplyr(warmTCs.df[, 2:17], 120, sd, fill = NA)) %>%
          mutate(`Local Time` = warmTCs.df$`Local Time`, .before = everything())

        title.main <- paste0("Spectrometer for Ice Nucleation (SPIN)")
        title.sub <-
          paste0("Thermocouple 120 Second Running SD Post Startup: ", date.c)

        plot.filename = paste0(export.plot.path, date.c, ' Thermocouple SD', '.png')

        print(paste0("Plotting: ", plot.filename))

        StackedBoxPlot(
          title.main,
          title.sub,
          coldTCs.SD.df,
          warmTCs.SD.df,
          y1.limits = c(0, 1.6),
          y2.limits = c(0, 1.6),
          y1.label = "Standard Deviations (\u00B0C)",
          y2.label = "Standard Deviations (\u00B0C)",
          plot.filename,
          plot.width = 10,
          plot.height = 10,
          plot.resolution.dpi = 400
        )
      }

      # ---------------------------------------------------------------------- #
      ##### PLOTTING: Thermocouple Setpoint Difference #####
      #'
      {

        coldTCs.Diff.df <- (coldTCs.df[, 2:17] - dataSPIN.df$`Cold Wall SP`[which(dataSPIN.df$`Local Time` %in% coldTCs.df$`Local Time`)]) %>%
          mutate(`Local Time` = coldTCs.df$`Local Time`, .before = everything())

        # Find difference between thermcouple value and SP
        warmTCs.Diff.df <- (warmTCs.df[, 2:17] - dataSPIN.df$`Warm Wall SP`[which(dataSPIN.df$`Local Time` %in% warmTCs.df$`Local Time`)]) %>%
          mutate(`Local Time` = warmTCs.df$`Local Time`, .before = everything())

        title.main <- paste0("Spectrometer for Ice Nucleation (SPIN)")
        title.sub <-
          paste0("Thermocouple Setpoint Difference: ", date.c)

        plot.filename = paste0(export.plot.path, date.c,
                               ' Thermocouple SP Difference',
                               '.png')

        print(paste0("Plotting: ", plot.filename))

        StackedBoxPlot(
          title.main,
          title.sub,
          coldTCs.Diff.df,
          warmTCs.Diff.df,
          y1.limits = c(-5, 5),
          y2.limits = c(-5, 5),
          y1.label = "Temperature (\u00B0C)",
          y2.label = "Temperature (\u00B0C)",
          plot.filename,
          plot.width = 10,
          plot.height = 10,
          plot.resolution.dpi = 400
        )
      }

      # ---------------------------------------------------------------------- #
      ##### PLOTTING: Thermocouple Mean Difference #####
      #'
      {
        coldTCs.MN.diff.df <- as.data.frame((coldTCs.df[, 2:17]) - rowMeans(coldTCs.df[, 2:17]), check.names = F) %>%
          mutate(`Local Time` = coldTCs.df$`Local Time`, .before = everything())

        warmTCs.MN.diff.df <- as.data.frame((warmTCs.df[, 2:17]) - rowMeans(warmTCs.df[, 2:17]), check.names = F) %>%
          mutate(`Local Time` = warmTCs.df$`Local Time`, .before = everything())

        title.main <- paste0("Spectrometer for Ice Nucleation (SPIN)")
        title.sub <-
          paste0("Thermocouple Difference from Mean: ", date.c)

        plot.filename = paste0(export.plot.path, date.c,
                               ' Thermocouple Mean Difference',
                               '.png')

        print(paste0("Plotting: ", plot.filename))

        StackedBoxPlot(
          title.main,
          title.sub,
          coldTCs.MN.diff.df,
          warmTCs.MN.diff.df,
          y1.limits = c(-5, 5),
          y2.limits = c(-5, 5),
          y1.label = "Temperature (\u00B0C)",
          y2.label = "Temperature (\u00B0C)",
          plot.filename,
          plot.width = 10,
          plot.height = 10,
          plot.resolution.dpi = 400
        )
      }

      # ---------------------------------------------------------------------- #
      ##### SECTION: Experiment Grouping #####
      #'

      {
        # How many experiment start sequences were logged
        ramps.n <- length(sequence.ramps.tm)

        # If more than one, add an ID to each for grouping later
        # Particularly important if two experiments were conducted in the same day
        if (ramps.n > 1){

          # Index points of when SPIN starts, ends, and the experiment times
          switch.points.nm <- diff(c(1, which(dataSPIN.df$`Local Time` %in% sequence.ramps.tm), nrow(dataSPIN.df)))

          tmp.index <- c()
          for (i in 1:length(switch.points.nm)){

            # Labels for experiments
            # 0 = "startup"
            tmp.index <- append(tmp.index, rep(i - 1, switch.points.nm[i]))
          }

          # Using diff above causes a 1 point offset, this corrects it
          tmp.index <- append(tmp.index, length(switch.points.nm) - 1)

          # Add ID variable
          dataSPIN.df <- dataSPIN.df %>%
            mutate(`Experiment Ramp ID` = tmp.index, .after = `Duration (s)`)

        } else if (ramps.n == 1){

          # If only one
          dataSPIN.df <- dataSPIN.df %>%
            mutate(`Experiment Ramp ID` = 1, .after = `Duration (s)`)
        } else {

          # If no experimental ramp started just list 0
          dataSPIN.df <- dataSPIN.df %>%
            mutate(`Experiment Ramp ID` = 0, .after = `Duration (s)`)
        }
      }

      # ---------------------------------------------------------------------- #
      ##### PLOTTING: Particle Size Spectrometer Time Series #####
      #'
      #'
      #'

      {
        # Only attempt to plot if there is particle data
        if (nrow(dataPBP.df) != 0){

          # Some days there was no ramp but particle data collected
          if (length(sequence.ramps.tm) == 0){

            # Find the point at which non-zero particle data is first measured
            cut.time <- dataSPIN.df$`Local Time`[first(which(dataSPIN.df$`0.55` != 0))]
            tmp.df <- dataSPIN.df %>% filter(`Local Time` >= cut.time)

            ID <- unique(tmp.df$`Experiment Ramp ID`)

            plot.filename = paste0(export.plot.path, date.c, ' Particle Time Series ',  "Experiment ", ID, '.png')

            print(paste0("Plotting: ", plot.filename))

            particle.levelplot.png(data = tmp.df,
                                   time.variable = NULL,
                                   title = paste0("Spectrometer for Ice Nucleation (SPIN)"),
                                   subtitle = paste0("Particle Size Distribution: ", date.c, ", Experiment ", ID),
                                   col.palette = NULL,
                                   time.type = NULL,
                                   plot.filename = plot.filename,
                                   plot.width = 12,
                                   plot.height = 6,
                                   plot.resolution.dpi = 600,
                                   optional.y = NULL)
          }

          if (length(sequence.ramps.tm) > 0){

            # Filter data after the ramp has started
            tmp.df <- dataSPIN.df %>%
              filter(`Local Time` >= first(sequence.ramps.tm))

            # Split by ramps
            tmp.ls <- tmp.df %>%
              group_split(`Experiment Ramp ID`)

            for (i in 1:length(sequence.ramps.tm)){

              # Split based on experiment ID
              tmp.df <- tmp.ls[[i]]

              if (nrow(tmp.df) >= 30*60){

                ID <- unique(tmp.df$`Experiment Ramp ID`)

                plot.filename = paste0(export.plot.path, date.c, ' Particle Time Series ',  "Experiment ", ID, '.png')

                print(paste0("Plotting: ", plot.filename))

                particle.levelplot.png(data = tmp.df,
                                       time.variable = NULL,
                                       title = paste0("Spectrometer for Ice Nucleation (SPIN)"),
                                       subtitle = paste0("Particle Size Distribution: ", date.c, ", Experiment ", ID),
                                       col.palette = NULL,
                                       time.type = NULL,
                                       plot.filename = plot.filename,
                                       plot.width = 12,
                                       plot.height = 6,
                                       plot.resolution.dpi = 600,
                                       optional.y = NULL)
              }
            }
          }
        }
      }

      # ------------------------------------------------------------------------ #
      ##### SECTION: Export Data #####
      #'
      {
        print(paste0("Exporting Level 0 Data: ", export.data.path))

        # Time variables
        {
          dataSPIN.df <- dataSPIN.df %>%
            mutate(`UTC Time` = with_tz(`Local Time`, tzone = "UTC"), .before = everything())
        }

        # Save data using data.table::fwrite
        data.table::fwrite(dataLOG.df, file = paste0(export.data.path, "SPIN001_Log_", spin.dirs[n], "_level0.csv"), showProgress = T)
        data.table::fwrite(dataPBP.df, file = paste0(export.data.path, "SPIN001_PbP_", spin.dirs[n], "_level0.csv"), showProgress = T)
        data.table::fwrite(dataSPIN.df, file = paste0(export.data.path, "SPIN001_SPIN_", spin.dirs[n], "_level0.csv"), showProgress = T)

        # Code benchmarking
        print(paste0(date.c, ', Elapsed Time (s) ', round((
          proc.time() - pct)[3], 2)))
      }
    } # END LOOP
  }
}
